#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v22
# autospec commit: 247c192
#
Name     : R-subselect
Version  : 0.16.0
Release  : 56
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/subselect_0.16.0.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/subselect_0.16.0.tar.gz
Summary  : Selecting Variable Subsets
Group    : Development/Tools
License  : GPL-2.0+
Requires: R-subselect-lib = %{version}-%{release}
Requires: R-ISwR
Requires: R-corpcor
BuildRequires : R-ISwR
BuildRequires : R-corpcor
BuildRequires : buildreq-R

%description
Package 'subselect' requires the Fortran LAPACK library. As of version
1.7 of R, LAPACK is included in R.

%package lib
Summary: lib components for the R-subselect package.
Group: Libraries

%description lib
lib components for the R-subselect package.


%prep
%setup -q -n subselect
pushd ..
cp -a subselect buildavx2
popd
pushd ..
cp -a subselect buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1743454472

%install
export SOURCE_DATE_EPOCH=1743454472
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/subselect/CHANGELOG
/usr/lib64/R/library/subselect/DESCRIPTION
/usr/lib64/R/library/subselect/INDEX
/usr/lib64/R/library/subselect/Meta/Rd.rds
/usr/lib64/R/library/subselect/Meta/data.rds
/usr/lib64/R/library/subselect/Meta/features.rds
/usr/lib64/R/library/subselect/Meta/hsearch.rds
/usr/lib64/R/library/subselect/Meta/links.rds
/usr/lib64/R/library/subselect/Meta/nsInfo.rds
/usr/lib64/R/library/subselect/Meta/package.rds
/usr/lib64/R/library/subselect/Meta/vignette.rds
/usr/lib64/R/library/subselect/NAMESPACE
/usr/lib64/R/library/subselect/R/subselect
/usr/lib64/R/library/subselect/R/subselect.rdb
/usr/lib64/R/library/subselect/R/subselect.rdx
/usr/lib64/R/library/subselect/data/Rdata.rdb
/usr/lib64/R/library/subselect/data/Rdata.rds
/usr/lib64/R/library/subselect/data/Rdata.rdx
/usr/lib64/R/library/subselect/doc/index.html
/usr/lib64/R/library/subselect/doc/subselect.R
/usr/lib64/R/library/subselect/doc/subselect.Rnw
/usr/lib64/R/library/subselect/doc/subselect.pdf
/usr/lib64/R/library/subselect/help/AnIndex
/usr/lib64/R/library/subselect/help/aliases.rds
/usr/lib64/R/library/subselect/help/paths.rds
/usr/lib64/R/library/subselect/help/subselect.rdb
/usr/lib64/R/library/subselect/help/subselect.rdx
/usr/lib64/R/library/subselect/html/00Index.html
/usr/lib64/R/library/subselect/html/R.css
/usr/lib64/R/library/subselect/readme

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/R/library/subselect/libs/subselect.so
/V4/usr/lib64/R/library/subselect/libs/subselect.so
/usr/lib64/R/library/subselect/libs/subselect.so
